flags/urls.py
from rest_framework.urlpatterns import format_suffix_patterns

from flags.views.views import FlagsView, FlagView
from variantgrid.perm_path import perm_path

rest_urlpatterns = [
    perm_path('api/flags/<flag_collection_id>', FlagsView.as_view(), name='flags_api'),
    perm_path('api/flag/<int:flag_id>', FlagView.as_view(), name='flag_api')
]

urlpatterns = format_suffix_patterns(rest_urlpatterns)

seqauto/urls.py
from rest_framework.urlpatterns import format_suffix_patterns

from library.django_utils.jqgrid_view import JQGridView
from seqauto import views, views_autocomplete, views_rest
from seqauto.grids.qc_data_grids import IlluminaFlowcellQCGrid, FastQCGrid, FlagstatsGrid, \
    QCExecSummaryGrid
from seqauto.grids.seqauto_grids import SeqAutoRunsGrid, EnrichmentKitGeneCoverageGrid, \
    GoldCoverageSummaryGrid, SequencingSamplesGrid, SequencingSamplesHistoricalGrid
from seqauto.grids.sequencing_data_grids import ExperimentsListGrid, SequencingRunListGrid, \
    UnalignedReadsListGrid, BamFileListGrid, VCFFileListGrid, QCFileListGrid, \
    EnrichmentKitListGrid
from seqauto.grids.sequencing_software_versions_grids import LibraryGrid, SequencerGrid, \
    AssayGrid, AlignerGrid, VariantCallerGrid, VariantCallingPipelineGrid
from seqauto.views import SequencerUpdate, LibraryUpdate, AssayUpdate, VariantCallerUpdate, \
    AlignerUpdate, VariantCallingPipelineUpdate
from variantgrid.perm_path import perm_path

urlpatterns = [
    perm_path('', views.sequencing_data, name='sequencing_data'),
    perm_path('seqauto_runs', views.seqauto_runs, name='seqauto_runs'),
    perm_path('experiments', views.experiments, name='experiments'),
    perm_path('sequencing_runs', views.sequencing_runs, name='sequencing_runs'),
    perm_path('unaligned_reads', views.unaligned_reads, name='unaligned_reads'),
    perm_path('bam_files', views.bam_files, name='bam_files'),
    perm_path('vcf_files', views.vcf_files, name='vcf_files'),
    perm_path('qcs', views.qcs, name='qcs'),
    perm_path('view_experiment/<experiment_id>', views.view_experiment, name='view_experiment'),
    perm_path('software_pipeline', views.software_pipeline, name='software_pipeline'),

    perm_path('enrichment_kits_list', views.enrichment_kits_list, name='enrichment_kits_list'),
    perm_path('enrichment_kit/<int:pk>', views.view_enrichment_kit, name='view_enrichment_kit'),

    perm_path('sequencing_stats', views.sequencing_stats, name='sequencing_stats'),
    perm_path('sequencing_stats/data', views.sequencing_stats_data, name='sequencing_stats_data'),
    perm_path('qc_data', views.qc_data, name='qc_data'),
    perm_path('sequencing_historical_graphs', views.sequencing_historical_graphs, name='sequencing_historical_graphs'),
    perm_path('graphs/qc_column_historical_graph/<int:qc_column_id>/<graph_type>/<enrichment_kit_separation>/<enrichment_kit_id>/<use_percent>', views.qc_column_historical_graph, name='qc_column_historical_graph'),
    perm_path('graphs/sequencing_run_qc_graph/<sequencing_run_id>/<qc_compare_type>', views.sequencing_run_qc_graph, name='sequencing_run_qc_graph'),
    perm_path('graphs/sequencing_run_qc_json_graph/<sequencing_run_id>/<qc_compare_type>', views.sequencing_run_qc_json_graph, name='sequencing_run_qc_json_graph'),

    perm_path('graphs/index_metrics_qc_graph/<illumina_qc_id>', views.index_metrics_qc_graph, name='index_metrics_qc_graph'),
    perm_path('graphs/qc_exec_summary_graph/<qc_exec_summary_id>/<qc_compare_type>', views.qc_exec_summary_graph, name='qc_exec_summary_graph'),
    perm_path('graphs/qc_exec_summary_json_graph/<qc_exec_summary_id>/<qc_compare_type>', views.qc_exec_summary_json_graph, name='qc_exec_summary_json_graph'),

    perm_path('view_seqauto_run/<int:seqauto_run_id>', views.view_seqauto_run, name='view_seqauto_run'),
    perm_path('view_sequencing_run/<sequencing_run_id>/tab/<int:tab_id>', views.view_sequencing_run, name='view_sequencing_run_tab'),
    perm_path('view_sequencing_run_stats_tab/<sequencing_run_id>', views.view_sequencing_run_stats_tab, name='view_sequencing_run_stats_tab'),
    perm_path('view_sequencing_run/<sequencing_run_id>', views.view_sequencing_run, name='view_sequencing_run'),
    perm_path('sequencing_run/reload_experiment_name/<sequencing_run_id>', views.reload_experiment_name, name='reload_experiment_name'),
    perm_path('sequencing_run/delete/<sequencing_run_id>', views.delete_sequencing_run, name='delete_sequencing_run'),
    perm_path('sequencing_run/assign_data_to_current_sample_sheet/<sequencing_run_id>', views.assign_data_to_current_sample_sheet, name='assign_data_to_current_sample_sheet'),

    perm_path('view_unaligned_reads/<int:unaligned_reads_id>', views.view_unaligned_reads, name='view_unaligned_reads'),
    perm_path('view_bam/<int:bam_file_id>', views.view_bam_file, name='view_bam_file'),
    perm_path('view_combo_vcf_file/<int:combo_vcf_file_id>', views.view_combo_vcf_file, name='view_combo_vcf_file'),
    perm_path('view_vcf/<int:vcf_file_id>', views.view_vcf_file, name='view_vcf_file'),
    perm_path('view_qc/<int:qc_id>', views.view_qc, name='view_qc'),
    perm_path('view_qc/view_qc_exec_summary_tab/<int:qc_id>', views.view_qc_exec_summary_tab, name='view_qc_exec_summary_tab'),
    perm_path('view_qc/view_qc_gene_list_tab/<int:qc_id>', views.view_qc_gene_list_tab, name='view_qc_gene_list_tab'),
    perm_path('view_qc/view_gene_coverage_collection_tab/<int:qc_id>', views.view_qc_gene_coverage_collection_tab, name='view_qc_gene_coverage_collection_tab'),
    perm_path('view_sample_qc_tab/<int:sample_id>', views.view_sample_qc_tab, name='view_sample_qc_tab'),
    perm_path('view_enrichment_kit_gene_coverage/<int:enrichment_kit_id>/<gene_symbol>', views.view_enrichment_kit_gene_coverage, name='view_enrichment_kit_gene_coverage'),
    perm_path('view_gold_coverage_summary/<int:pk>', views.view_gold_coverage_summary, name='view_gold_coverage_summary'),

    # Grids
    perm_path('seqauto_runs/grid/<slug:op>/', JQGridView.as_view(grid=SeqAutoRunsGrid), name='seqauto_runs_grid'),
    perm_path('experiments/grid/<slug:op>/', JQGridView.as_view(grid=ExperimentsListGrid, delete_row=True), name='experiments_grid'),
    perm_path('sequencing_run/grid/<slug:op>/', JQGridView.as_view(grid=SequencingRunListGrid), name='sequencing_run_grid'),
    perm_path('unaligned_reads/grid/<slug:op>/', JQGridView.as_view(grid=UnalignedReadsListGrid), name='unaligned_reads_grid'),
    perm_path('bam_file/grid/<slug:op>/', JQGridView.as_view(grid=BamFileListGrid), name='bam_file_grid'),
    perm_path('vcf_file/grid/<slug:op>/', JQGridView.as_view(grid=VCFFileListGrid), name='vcf_file_grid'),
    perm_path('qc/grid/<slug:op>/', JQGridView.as_view(grid=QCFileListGrid), name='qc_grid'),
    perm_path('enrichment_kit/grid/<slug:op>/', JQGridView.as_view(grid=EnrichmentKitListGrid), name='enrichment_kit_list_grid'),
    perm_path('enrichment_kit/gene/grid/<int:enrichment_kit_id>/<genome_build_name>/<gene_symbol>/<slug:op>/', JQGridView.as_view(grid=EnrichmentKitGeneCoverageGrid), name='enrichment_kit_gene_coverage_grid'),
    perm_path('gold_coverage_summary/grid/<pk>/<slug:op>/', JQGridView.as_view(grid=GoldCoverageSummaryGrid), name='gold_coverage_summary_grid'),
    perm_path('sequencing_stats/sequencing_samples/grid/<slug:op>/', JQGridView.as_view(grid=SequencingSamplesGrid, csv_download=True), name='sequencing_samples_grid'),
    perm_path('sequencing_stats/sequencing_samples_historical/grid/<slug:time_frame>/<slug:op>/', JQGridView.as_view(grid=SequencingSamplesHistoricalGrid, csv_download=True), name='sequencing_samples_historical_grid'),
    # QC Data
    perm_path('illumina_flowcell_qc/grid/<slug:op>/', JQGridView.as_view(grid=IlluminaFlowcellQCGrid, csv_download=True), name='illumina_flowcell_qc_grid'),
    perm_path('fastqc/grid/<slug:op>/', JQGridView.as_view(grid=FastQCGrid, csv_download=True), name='fastqc_grid'),
    perm_path('flagstats/grid/<slug:op>/', JQGridView.as_view(grid=FlagstatsGrid, csv_download=True), name='flagstats_grid'),
    perm_path('qc_exec_summary/grid/<slug:op>/', JQGridView.as_view(grid=QCExecSummaryGrid, csv_download=True), name='qc_exec_summary_grid'),
    # Software/settings
    perm_path('sequencing_software_versions/library/grid/<slug:op>/', JQGridView.as_view(grid=LibraryGrid), name='library_grid'),
    perm_path('sequencing_software_versions/sequencer/grid/<slug:op>/', JQGridView.as_view(grid=SequencerGrid), name='sequencer_grid'),
    perm_path('sequencing_software_versions/assay/grid/<slug:op>/', JQGridView.as_view(grid=AssayGrid), name='assay_grid'),
    perm_path('sequencing_software_versions/aligner/grid/<slug:op>/', JQGridView.as_view(grid=AlignerGrid), name='aligner_grid'),
    perm_path('sequencing_software_versions/variant_caller/grid/<slug:op>/', JQGridView.as_view(grid=VariantCallerGrid), name='variant_caller_grid'),
    perm_path('sequencing_software_versions/variant_calling_pipeline/grid/<slug:op>/', JQGridView.as_view(grid=VariantCallingPipelineGrid), name='variant_calling_pipeline_grid'),

    perm_path('sequencing_software_versions', views.sequencing_software_versions, name='sequencing_software_versions'),
    perm_path('view_sequencer/<pk>', SequencerUpdate.as_view(), name='view_sequencer'),
    perm_path('view_library/<pk>', LibraryUpdate.as_view(), name='view_library'),
    perm_path('view_assay/<pk>', AssayUpdate.as_view(), name='view_assay'),
    perm_path('view_variant_caller/<pk>', VariantCallerUpdate.as_view(), name='view_variant_caller'),
    perm_path('view_aligner/<pk>', AlignerUpdate.as_view(), name='view_aligner'),
    perm_path('view_variant_calling_pipeline/<pk>', VariantCallingPipelineUpdate.as_view(), name='view_variant_calling_pipeline'),

    # Autocompletes
    perm_path('autocomplete/QCColumn/', views_autocomplete.QCColumnAutocompleteView.as_view(), name='qc_column_autocomplete'),
    perm_path('autocomplete/EnrichmentKit/', views_autocomplete.EnrichmentKitAutocompleteView.as_view(), name='enrichment_kit_autocomplete'),
    perm_path('autocomplete/SequencingRun/', views_autocomplete.SequencingRunAutocompleteView.as_view(),
              name='sequencing_run_autocomplete'),
]

#router = routers.DefaultRouter()
rest_urlpatterns = [
    perm_path('api/view_enrichment_kit_summary/<int:pk>', views_rest.EnrichmentKitSummaryView.as_view(), name='api_view_enrichment_kit_summary'),

seqauto/models/models_enums.py
# Using own file to stop circular dependencies in illuminate_report
from django.db import models

from library.utils import Constant


class QCGraphEnrichmentKitSeparationChoices(models.TextChoices):
    ALL_ENRICHMENT_KITS = 'A', 'All Enrichment Kits'
    SEPARATED_ENRICHMENT_KITS = 'S', 'Separated Enrichment Kit'
    SELECTED_ENRICHMENT_KIT = 'O', 'User selected Enrichment Kit'

    SHOW_ENRICHMENT_KIT = Constant({SELECTED_ENRICHMENT_KIT[0]: True})

    def show_enrichment_kit(self):
        return QCGraphEnrichmentKitSeparationChoices.SHOW_ENRICHMENT_KIT.get(self.value)


class QCGraphType(models.TextChoices):
    LINE_GRAPH = 'L', 'Line Graph'
    BOX_PLOT = 'B', 'Box Plot'


class QCGraphTypes2(models.TextChoices):
    BOX_PLOT = 'B', 'Box Plot'
    BAR_CHART = 'A', 'Bar Chart'


class QCCompareType(models.TextChoices):
    GOLD_ENRICHMENT_KIT_RUNS = 'G', 'Gold Enrichment Kit Runs'
    ENRICHMENT_KIT = 'P', 'Enrichment Kit'
    SEQUENCER = 'S', 'Sequencer'
    ALL_RUNS = 'A', 'All Runs'
    SEQUENCING_RUN = 'R', 'SequencingRun'

    ENRICHMENT_KIT_TYPES = Constant((GOLD_ENRICHMENT_KIT_RUNS[0], ENRICHMENT_KIT[0]))


class SequencingFileType(models.TextChoices):
    SAMPLE_SHEET = 'S', 'SampleSheet'
    ILLUMINA_FLOWCELL_QC = 'I', 'Illumina_Flowcell_QC'
    FASTQ = 'U', 'FastQ'  # Unmapped
    FASTQC = 'F', 'FastQC'
    BAM = 'B', 'Bam'
    FLAGSTATS = 'T', 'Flagstats'
    VCF = 'V', 'VCF'
    COMBINED_VCF = 'C', 'CombinedVCF'
    QC = 'Q', 'QC'
    DATA_MIGRATION = 'M', "Data Migration"


class JobScriptStatus(models.TextChoices):
    CREATED = 'C', 'Created'
    SUBMITTED = 'S', 'Submitted'
    FINISHED = 'F', 'Finished'


class DataGeneration(models.TextChoices):
    HISEQ = 'H', 'HiSeq'
    MISEQ = 'M', 'MiSeq'


class PairedEnd(models.TextChoices):
    R1 = "R1"
    R2 = "R2"


class SequencerRead(models.TextChoices):
    R1 = "R1"
    R2 = "R2"
    I1 = "I1"
    I2 = "I2"


class SeqAutoRunStatus(models.TextChoices):
    CREATED = 'c', "Created"
    SCANNING_FILES = 's', "Scanning Files"
    CREATE_MODELS = 'm', "Create Models"
    SCRIPTS_AND_JOBS = 'j', "Scripts and Jobs"
    FINISHED = 'F', "Finished"
    ERROR = 'E', "Error"

    COMPLETED_STATES = Constant([FINISHED[0], ERROR[0]])


class EnrichmentKitType(models.TextChoices):
    AMPLICON = 'A', 'Amplicon'
    CAPTURE = 'C', 'Capture'
    VIRTUAL = 'V', 'Virtual'

seqauto/forms.py
from dal import forward
from django import forms

from library.django_utils.autocomplete_utils import ModelSelect2
from library.forms import ROFormMixin
from seqauto import models
from seqauto.models import QCType, QCColumn, EnrichmentKit, SequencingRun
from seqauto.models.models_enums import QCCompareType, QCGraphTypes2, \
    QCGraphEnrichmentKitSeparationChoices, QCGraphType
from snpdb.forms import BaseDeclareForm


class QCCompareTypeForm(forms.Form):

    def __init__(self, *args, columns, compare_against=None, **kwargs):
        super().__init__(*args, **kwargs)
        column_choices = [(x, x) for x in columns]
        self.fields['column'].choices = column_choices
        if compare_against:
            filtered_choices = [(k, v) for k, v in QCCompareType.choices if k in compare_against]
            self.fields['compare_against'].choices = filtered_choices

    compare_against = forms.ChoiceField(choices=QCCompareType.choices)
    graph_type = forms.ChoiceField(choices=QCGraphTypes2.choices)
    column = forms.ChoiceField()


class SequencingRunForm(forms.ModelForm):

    class Meta:
        model = models.SequencingRun
        fields = ('bad', 'hidden')


class BamFileForm(forms.ModelForm, ROFormMixin):
    class Meta:
        model = models.BamFile
        fields = ('path', 'aligner', 'data_state')
        read_only = ('path', 'aligner', 'data_state')


class VCFFileForm(forms.ModelForm, ROFormMixin):
    class Meta:
        model = models.VCFFile
        fields = ('path', 'bam_file', 'variant_caller')
        read_only = ('path', 'bam_file', 'variant_caller')


class QCFileForm(forms.ModelForm, ROFormMixin):
    class Meta:
        model = models.QC
        fields = ('path', 'bam_file', 'vcf_file', 'data_state')
        read_only = ('path', 'bam_file', 'vcf_file', 'data_state')


class QCColumnForm(BaseDeclareForm):
    qc_type = forms.ModelChoiceField(queryset=QCType.objects.all(), label='QC type')
    qc_column = forms.ModelChoiceField(queryset=QCColumn.objects.all(),
                                       label='QC column',
                                       widget=ModelSelect2(url='qc_column_autocomplete',
                                                           forward=['qc_type'],
                                                           attrs={'data-placeholder': 'Column...'}))
    enrichment_kit_separation = forms.ChoiceField(choices=QCGraphEnrichmentKitSeparationChoices.choices)
    enrichment_kit = forms.ModelChoiceField(queryset=EnrichmentKit.objects.all())
    qc_graph_type = forms.ChoiceField(choices=QCGraphType.choices, label='QC graph type')


class EnrichmentKitForm(forms.Form):
    """ Only returns non-obsolete kits """
    enrichment_kit = forms.ModelChoiceField(queryset=EnrichmentKit.objects.all(),
                                            widget=ModelSelect2(url='enrichment_kit_autocomplete',
                                                                attrs={'data-placeholder': 'Enrichment Kit...'}))


class AllEnrichmentKitForm(forms.Form):
    """ Also returns obsolete kits """
    enrichment_kit = forms.ModelChoiceField(queryset=EnrichmentKit.objects.all(),
                                            widget=ModelSelect2(url='enrichment_kit_autocomplete',
                                                                forward=(forward.Const(True, 'show_obsolete'),),
                                                                attrs={'data-placeholder': 'Enrichment Kit...'}))


class AutocompleteSequencingRunForm(forms.Form):
    sequencing_run = forms.ModelChoiceField(queryset=SequencingRun.objects.all(),
                                            widget=ModelSelect2(url='sequencing_run_autocomplete',
                                                                attrs={'data-placeholder': 'SequencingRun...'}))

seqauto/templates/seqauto/tabs/view_qc_exec_summary_tab.html
{% load static %}
{% load jqgrid_tags %}
{% load help_tags %}
{% load model_helpers %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="{% static 'css/graphs.css' %}" />
<style>
#qc-exec-summary-graph {
    width: 1200px;
    height: 800px;
}


.qc-column-name {
	text-align: right;
}

/* Fix to override global_legacy.scss */
table th.num, table td.num {
    text-align: left;
}

</style>
<script src="{% static 'js/generated_graphs.js' %}"></script>
<script>
{% if qc.data_state == 'C' and exec_summary.data_state == 'C' %}
    EXEC_SUMMARY_ID = {{ exec_summary.pk }};

	function loadQCExecSummaryGraph() {
        const esSelector = $("#exec-summary");
		const graph_selector = $('#qc-exec-summary-graph');
		const compare_against = $('#id_compare_against', esSelector).val();
        const graph_type = $('#id_graph_type', esSelector).val();

        clearGraph(graph_selector);
        const columnSelect = $("select#id_column", esSelector).parent();
        if (graph_type == 'B') {
            columnSelect.hide();
            const POLL_URL = Urls.qc_exec_summary_graph(EXEC_SUMMARY_ID, compare_against);
            poll_graph_status(graph_selector, POLL_URL, Urls.cached_generated_file_delete());
        } else if (graph_type == 'A') {
            columnSelect.show();
            const JSON_GRAPH_URL = Urls.qc_exec_summary_json_graph(EXEC_SUMMARY_ID, compare_against);
            graph_selector.load(JSON_GRAPH_URL, function() { graph_selector.removeClass("graph-loading"); });
        }
	}
{% endif %}

    $(document).ready(function() {
    	{% if qc.data_state == 'C' and exec_summary %}
    	loadQCExecSummaryGraph();
    	$('#id_compare_against', "#exec-summary").change(loadQCExecSummaryGraph);
        $('#id_graph_type', "#exec-summary").change(loadQCExecSummaryGraph);

    	{% endif %}
    });
</script>

<div id="exec-summary">
    {% if qc.data_state == 'C' and exec_summary.data_state == 'C' %}
        {% crispy graph_form form_helper.horizontal %}
		<div id='qc-exec-summary-graph' class='generated-graph'></div>

        <table class="table">
            {{ exec_summary | as_table | safe }}
        </table>
    {% else %}
        {% if exec_summary %}
            Exec summary is not ready (status={{ exec_summary.get_data_state_display }})
        {% else %}
            Exec summary not available.
        {% endif %}
	{% endif %}
				
</div>

seqauto/templates/seqauto/tabs/view_qc_gene_coverage_collection_tab.html
{% load jqgrid_tags %}
<style>
.qc-column-name {
	text-align: right;
}
</style>
{% if gene_coverage %}
<div id="gene-coverage">
{% jqgrid 'gene_coverage_collection_grid' 'GeneCoverage' False None 'jqgrid/jqgrid.html' None False download_grid_json_as_csv=True gene_coverage_collection_id=gene_coverage.pk %}
</div>
{% endif %}

seqauto/templates/seqauto/tabs/view_qc_gene_list_tab.html
{% load jqgrid_tags %}
{% load help_tags %}
<div id="qc-gene-list">
    {% page_help user 'seqauto/sample_qc_gene_list' 'Sample QC Gene List' %}

    {% for qc_gene_list in qc.qcgenelist_set.all %}

        {% if qc_gene_list.custom_text_gene_list.gene_list.import_status == 'S' %}
            <h3>QC Gene List</h3>

            {% jqgrid 'gene_list_genes_grid' qc_gene_list.custom_text_gene_list.gene_list.pk search=False download_grid_json_as_csv=True gene_list_id=qc_gene_list.custom_text_gene_list.gene_list.pk %}
        {% else %}
            <b>Error:</b>
            {% if qc_gene_list.custom_text_gene_list.gene_list.import_status == 'E' %}
                <pre>
                 {{ qc_gene_list.custom_text_gene_list.gene_list.error_message }}
                </pre>
            {% else %}
                Unknown Error.
            {% endif %}
        {% endif %}
    {% endfor %}
</div>

seqauto/templates/seqauto/tabs/view_sample_qc_tab.html
<script>
$(document).ready(function() {
    var sequencingRunQCTabUrl = "{% url 'view_sequencing_run_stats_tab' sample.sequencing_run.pk %}";
    $("#sequencing-run-qc").load(sequencingRunQCTabUrl);

{% if qc %}
    $("#qc-exec-summary").load("{% url 'view_qc_exec_summary_tab' qc.pk %}");
    $("#qc-gene-coverage").load("{% url 'view_qc_gene_coverage_collection_tab' qc.pk %}");
{% endif %}

});
</script>

<h3>{{ sample.sequencing_run }}</h3>
<div id='sequencing-run-qc'>

</div>


<h3>Sample QC</h3>
<div id='qc-exec-summary'>

</div>

<h3>Gene Coverage</h3>
<div id='qc-gene-coverage'>

</div>

seqauto/templates/seqauto/tabs/view_sequencing_run_stats_tab.html
{% load static %}
{% load model_helpers %}
{% load seqauto_record_tags %}
<link rel="stylesheet" href="{% static 'css/graphs.css' %}" />
<link rel="stylesheet" href="{% static 'css/seqauto.css' %}" />
<script src="{% static 'js/generated_graphs.js' %}"></script>
<script>
	var DELETE_URL = "{% url 'cached_generated_file_delete' %}";
	var BASE_QC_POLL_URL = "{% url 'sequencing_run_qc_graph' sequencing_run.pk 'QC_COMPARE_TYPE' %}";
	var BASE_QC_JSON_GRAPH_URL = "{% url 'sequencing_run_qc_json_graph' sequencing_run.pk 'QC_COMPARE_TYPE' %}";

	function loadSequencingRunQCGraph() {
	    const SEQUENCING_RUN_ID = "{{ sequencing_run.pk }}";
        const rsSelector = $("#run-stats");
		const graph_selector = $('#generated-graph-qc', rsSelector);
		const compare_against = $('#id_compare_against', rsSelector).val();
		const graph_type = $('#id_graph_type', rsSelector).val();

		clearGraph(graph_selector);
		const columnSelect = $("select#id_column", rsSelector).parent();
		if (graph_type == 'B') {
			columnSelect.hide();
			const POLL_URL = Urls.sequencing_run_qc_graph(SEQUENCING_RUN_ID, compare_against);
			poll_graph_status(graph_selector, POLL_URL, Urls.cached_generated_file_delete());
		} else if (graph_type == 'A') {
			columnSelect.show();
			const JSON_GRAPH_URL = Urls.sequencing_run_qc_json_graph(SEQUENCING_RUN_ID, compare_against);
			graph_selector.load(JSON_GRAPH_URL, function() { graph_selector.removeClass("graph-loading"); });
		}
	}

$(document).ready(function() {
	{% if show_stats %}
		loadSequencingRunQCGraph();
		
		$('#id_compare_against', "#run-stats").change(loadSequencingRunQCGraph);
		$('#id_graph_type', "#run-stats").change(loadSequencingRunQCGraph);

	{% endif %}
});
</script>
<div id="run-stats">
{% if show_stats %}
	{{ graph_form.as_p }}
	<div id='generated-graph-qc' class='generated-graph'></div>
	<table class='model-table'>
		<tr><th>Mean Cluster Density:		<td>{{ illumina_qc.mean_cluster_density }}
		<tr><th>Mean PF Cluster Density:	<td>{{ illumina_qc.mean_pf_cluster_density }}
		<tr><th>Total Clusters:				<td>{{ illumina_qc.total_clusters }}
		<tr><th>Total PF Clusters:			<td>{{ illumina_qc.total_pf_clusters }}
		<tr><th>Percentage of Clusters PF:	<td>{{ illumina_qc.percentage_of_clusters_pf }}
		<tr><th>Aligned To PhiX:			<td>{{ illumina_qc.aligned_to_phix }}
		{% if read_q30s %}
		<tr><th>R1 Q30:			<td>{{ read_q30s.R1 | floatformat }}
		<tr><th>R2 Q30:			<td>{{ read_q30s.R2 | floatformat }}
		{% endif %}
		</tr>
	</table>
{% else %}
	{% if sequencing_run.can_generate_qc %}
		{% record_data_state_helper illumina_qc %}
	{% else %}
	    Can't generate QC for this SequencingRun due to missing metrics files.
	{% endif %} 
{% endif %}
</div>