analysis/urls.py
from analysis.grids import AnalysesGrid, NodeColumnSummaryGrid, KaromappingAnalysesGrid, AnalysisTemplatesGrid, \
    AnalysisNodeIssuesGrid, NodeOntologyGenesGrid, NodeGeneDiseaseClassificationGenesGrid, \
    NodeTissueExpressionGenesGrid, NodeTissueUniProtTissueSpecificityGenesGrid
from analysis.views import views, views_json, views_grid, views_karyomapping, views_autocomplete
from library.django_utils.jqgrid_view import JQGridView
from variantgrid.perm_path import perm_path

urlpatterns = [
    perm_path('analyses/list/', views.analysis_list, name='analyses'),
    perm_path('analysis_templates/', views.analysis_templates, name='analysis_templates'),
    perm_path('<int:analysis_id>/', views.view_analysis, name='analysis'),
    perm_path('<int:analysis_id>/<int:active_node_id>/', views.view_analysis, name='analysis_node'),
    perm_path('clone_analysis/<int:analysis_id>/', views_json.clone_analysis, name='clone_analysis'),
    perm_path('create_analysis_from_template/<genome_build_name>', views.create_analysis_from_template, name='create_analysis_from_template'),
    perm_path('trio_wizard/<int:cohort_id>/<int:sample1_id>/<int:sample2_id>/<int:sample3_id>/', views.trio_wizard, name='trio_wizard'),

    # Templates
    perm_path('analysis_template/<pk>/save/', views_json.analysis_template_save, name='analysis_template_save'),
    perm_path('analysis_template/<pk>/list/', views.analysis_templates_list, name='analysis_templates_list'),

    # For node views below - a Node contains the analysis ID - so we don't need to pass analysis_id, but do so
    # to make it easier to debug errors if nodes were deleted

    # Node editors
    perm_path('<int:analysis_id>/<int:analysis_version>/node/view/<int:node_id>/<int:node_version>/<slug:extra_filters>/', views.node_view, name='node_view'),
    perm_path('<int:analysis_id>/node_update/<int:node_id>/', views_json.NodeUpdate.as_view(), name='node_update'),
    perm_path('<int:analysis_id>/<int:analysis_version>/node_debug/<int:node_id>/<int:node_version>/<slug:extra_filters>/', views.node_debug, name='node_debug'),
    perm_path('<int:analysis_id>/node_doc/<int:node_id>/', views.node_doc, name='node_doc'),
    perm_path('<int:analysis_id>/node_load/<int:node_id>/', views.node_load, name='node_load'),
    perm_path('<int:analysis_id>/node_cancel_load/<int:node_id>/', views.node_cancel_load, name='node_cancel_load'),
    perm_path('<int:analysis_id>/<int:analysis_version>/node/column_summary/<int:node_id>/<int:node_version>/<slug:extra_filters>/<slug:grid_column_name>/<int:significant_figures>/', views.node_column_summary, name='node_column_summary'),
    perm_path('<int:analysis_id>/node/node_snp_matrix/<int:node_id>/<int:node_version>/<slug:conversion>/<int:significant_figures>/', views.node_snp_matrix, name='node_snp_matrix'),
    perm_path('<int:analysis_id>/<int:analysis_version>/node/graph/<int:node_id>/<int:node_version>/<slug:graph_type_id>/<slug:cmap>/', views.node_data_graph, name='node_data_graph'),
    perm_path('<int:analysis_id>/node/cohort_zygosity_filters/<int:node_id>/<int:cohort_id>/', views.cohort_zygosity_filters, name='cohort_zygosity_filters'),
    perm_path('<int:analysis_id>/node/vcf_locus_filters/<int:node_id>/<int:vcf_id>/', views.vcf_locus_filters, name='vcf_locus_filters'),
    perm_path('<int:analysis_id>/node/sample_vcf_locus_filters/<int:node_id>/<int:sample_id>/', views.sample_vcf_locus_filters, name='sample_vcf_locus_filters'),
    perm_path('<int:analysis_id>/node/cohort_vcf_locus_filters/<int:node_id>/<int:cohort_id>/', views.cohort_vcf_locus_filters, name='cohort_vcf_locus_filters'),
    perm_path('<int:analysis_id>/node/pedigree_vcf_locus_filters/<int:node_id>/<int:pedigree_id>/', views.pedigree_vcf_locus_filters, name='pedigree_vcf_locus_filters'),

    # Node JSON
    perm_path('<int:analysis_id>/node/<int:node_id>/data/', views_json.node_data, name='node_data'),
    perm_path('<int:analysis_id>/node/create/<node_type>/', views_json.node_create, name='node_create'),
    perm_path('<int:analysis_id>/nodes/copy/', views_json.nodes_copy, name='nodes_copy'),
    perm_path('<int:analysis_id>/nodes/delete/', views_json.nodes_delete, name='nodes_delete'),
    perm_path('<int:analysis_id>/nodes/status/', views_json.nodes_status, name='nodes_status'),
    perm_path('<int:analysis_id>/node/tasks/', views_json.nodes_tasks, name='nodes_tasks'),

    perm_path('<int:analysis_id>/create_filter_child/<int:node_id>/', views_json.create_filter_child, name='create_filter_child'),
    perm_path('<int:analysis_id>/create_extra_filter_child/<int:node_id>/<slug:extra_filters>/', views_json.create_extra_filter_child, name='create_extra_filter_child'),
    perm_path('<int:analysis_id>/create_selected_child/<int:node_id>/', views_json.create_selected_child, name='create_selected_child'),

    perm_path('<int:analysis_id>/node_versions/', views_json.analysis_node_versions, name='analysis_node_versions'),
    perm_path('<int:analysis_id>/edit_and_grid/', views.analysis_editor_and_grid, name='analysis_editor_and_grid'),
    perm_path('<int:analysis_id>/edit_and_grid/stand_alone/', views.stand_alone_analysis_editor_and_grid, name='standalone_analysis_editor_and_grid'),

    perm_path('<int:analysis_id>/set_panel_size/', views_json.analysis_set_panel_size, name='analysis_set_panel_size'),
    perm_path('<int:analysis_id>/node_populate_clingen_alleles/<int:node_id>/', views_json.node_populate_clingen_alleles,
              name='node_populate_clingen_alleles'),
    perm_path('<int:analysis_id>/settings/lock', views.analysis_settings_lock, name='analysis_settings_lock'),
    perm_path('<int:analysis_id>/settings/', views.view_analysis_settings, name='analysis_settings'),
    perm_path('<int:analysis_id>/settings_details_tab/', views.analysis_settings_details_tab, name='analysis_settings_details_tab'),
    perm_path('<int:analysis_id>/settings_node_counts_tab/', views.analysis_settings_node_counts_tab, name='analysis_settings_node_counts_tab'),
    perm_path('<int:analysis_id>/settings_template_run_tab/', views.analysis_settings_template_run_tab,
              name='analysis_settings_template_run_tab'),
    perm_path('<int:analysis_id>/reload/', views_json.analysis_reload, name='analysis_reload'),
    perm_path('<int:analysis_id>/input_samples/', views.analysis_input_samples, name='analysis_input_samples'),
    perm_path('sample_patient_gene_disease/<int:sample_id>', views_json.sample_patient_gene_disease, name='sample_patient_gene_disease'),

    perm_path('<int:analysis_id>/node_graph/<int:node_id>/<int:graph_type_id>/<slug:cmap>/', views.node_graph, name='node_graph'),
    perm_path('<int:analysis_id>/column_summary_boxplot/<int:node_id>/<label>/<slug:variant_column>/', views.column_summary_boxplot, name='column_summary_boxplot'),
    perm_path('<int:analysis_id>/set_variant_selected/<int:node_id>/', views_json.set_variant_selected, name='set_variant_selected'),

    perm_path('set_variant_tag/<slug:location>/', views_json.set_variant_tag, name='set_variant_tag'),

    perm_path('<int:analysis_id>/classification/create_for_variant_tag/<int:variant_tag_id>', views.CreateClassificationForVariantTagView.as_view(),
              name='create_classification_for_variant_tag'),
    perm_path('<int:analysis_id>/create_classification/',
              views.create_classification_for_analysis, name='create_classification_for_analysis'),

    # Node Data (bottom right window)
    perm_path('<int:analysis_id>/<int:analysis_version>/node_data_grid/cfg/<int:node_id>/<int:node_version>/<slug:extra_filters>/', views.node_data_grid, name='node_data_grid'),
    perm_path('<int:analysis_id>/<int:analysis_version>/node_async_wait/<int:node_id>/<int:node_version>/<slug:extra_filters>/', views.node_async_wait, name='node_async_wait'),
    perm_path('<int:analysis_id>/<int:analysis_version>/node_errors/<int:node_id>/<int:node_version>/<slug:extra_filters>/', views.node_errors, name='node_errors'),
    perm_path('<int:analysis_id>/node_method_description/<int:node_id>/<int:node_version>', views.node_method_description, name='node_method_description'),

    # Analysis templates
    perm_path('<int:analysis_id>/templates/variable/<int:node_id>/', views_json.analysis_template_variable, name='analysis_template_variable'),

    # Grids
    perm_path('<int:analysis_id>/node_grid/export/', views_grid.node_grid_export, name='node_grid_export'),
    perm_path('<int:analysis_id>/<int:analysis_version>/node_grid/cfg/<int:node_id>/<int:node_version>/<slug:extra_filters>/', views_grid.NodeGridConfig.as_view(), name='node_grid_config'),
    perm_path('<int:analysis_id>/node_grid/handler/', views_grid.NodeGridHandler.as_view(), name='node_grid_handler'),

    perm_path('<int:analysis_id>/node_column_summary/grid/<int:node_id>/<int:node_version>/<slug:extra_filters>/<slug:variant_column>/<int:significant_figures>/<slug:op>/', JQGridView.as_view(grid=NodeColumnSummaryGrid, csv_download=True), name='node_column_summary_grid'),
    perm_path('analyses/grid/<slug:op>/', JQGridView.as_view(grid=AnalysesGrid, delete_row=True), name='analyses_grid'),

    perm_path('analysis_templates/grid/<slug:op>/', JQGridView.as_view(grid=AnalysisTemplatesGrid, delete_row=True), name='analysis_templates_grid'),
    perm_path('analysis_issues/grid/<slug:op>/',
              JQGridView.as_view(grid=AnalysisNodeIssuesGrid), name='analysis_node_issues_grid'),

    perm_path('<int:analysis_id>/node/ontology/genes/grid/<int:node_id>/<int:version>/<slug:op>/',
              JQGridView.as_view(grid=NodeOntologyGenesGrid), name='node_ontology_genes_grid'),
    perm_path('<int:analysis_id>/node/gene_disease_classification/grid/<int:node_id>/<int:version>/<slug:op>/',
              JQGridView.as_view(grid=NodeGeneDiseaseClassificationGenesGrid),
              name='node_gene_disease_classification_genes_grid'),

    perm_path('<int:analysis_id>/node/tissue/genes/grid/<int:node_id>/<int:version>/<slug:op>/',

flags/urls.py
from rest_framework.urlpatterns import format_suffix_patterns

from flags.views.views import FlagsView, FlagView
from variantgrid.perm_path import perm_path

rest_urlpatterns = [
    perm_path('api/flags/<flag_collection_id>', FlagsView.as_view(), name='flags_api'),
    perm_path('api/flag/<int:flag_id>', FlagView.as_view(), name='flag_api')
]

urlpatterns = format_suffix_patterns(rest_urlpatterns)

analysis/models/models_variant_tag.py
from typing import List

from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE, SET_NULL, PROTECT, Q
from django_extensions.db.models import TimeStampedModel

from analysis.models.enums import TagLocation
from analysis.models.models_analysis import Analysis
from analysis.models.nodes.analysis_node import AnalysisNode
from library.django_utils.guardian_permissions_mixin import GuardianPermissionsAutoInitialSaveMixin
from snpdb.models import Variant, GenomeBuild, Tag, VariantAllele, Allele


class VariantTagsImport(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=CASCADE)
    genome_build = models.ForeignKey(GenomeBuild, on_delete=CASCADE)

    def __str__(self):
        num_tags = self.importedvarianttag_set.count()
        return f"{num_tags} tags ({self.genome_build}) by {self.user} on {self.created}"


class ImportedVariantTag(models.Model):
    """ Contains all data as not everything will match etc """
    variant_tags_import = models.ForeignKey(VariantTagsImport, on_delete=CASCADE)
    variant_string = models.TextField()
    genome_build_string = models.TextField()
    gene_symbol_string = models.TextField(null=True)
    tag_string = models.TextField()
    variant_id = models.IntegerField()
    analysis_id = models.IntegerField(null=True)
    node_id = models.IntegerField(null=True)
    analysis_name = models.TextField(null=True)
    username = models.TextField()
    created = models.DateTimeField()  # Time on original server


class VariantTag(GuardianPermissionsAutoInitialSaveMixin, TimeStampedModel):
    """ A tag in an analysis. Has create create/delete signal handlers:
        @see analysis.signals.signal_handlers._update_analysis_on_variant_tag_change """
    variant = models.ForeignKey(Variant, on_delete=PROTECT)
    allele = models.ForeignKey(Allele, null=True, on_delete=PROTECT)  # moved to own field as an optimisation
    genome_build = models.ForeignKey(GenomeBuild, on_delete=CASCADE)
    tag = models.ForeignKey(Tag, on_delete=CASCADE)
    analysis = models.ForeignKey(Analysis, null=True, on_delete=SET_NULL)
    location = models.CharField(max_length=1, choices=TagLocation.choices, default=TagLocation.ANALYSIS)
    imported_variant_tag = models.ForeignKey(ImportedVariantTag, null=True, on_delete=CASCADE)
    # Most recent node where it was added
    node = models.ForeignKey(AnalysisNode, null=True, on_delete=SET_NULL)  # Keep even if node deleted
    user = models.ForeignKey(User, on_delete=CASCADE)

    def can_view(self, user):
        """ Delegate to Analysis if set """
        if self.analysis:
            return self.analysis.can_view(user)
        return super().can_view(user)

    def can_write(self, user):
        """ Delegate to Analysis if set """
        if self.analysis:
            return self.analysis.can_write(user)
        return super().can_write(user)

    @property
    def canonical_c_hgvs(self):
        return self.variant.get_canonical_c_hgvs(self.genome_build)

    @property
    def gene_symbol(self):
        gs = None
        if cta := self.variant.get_canonical_transcript_annotation(self.genome_build):
            if tv := cta.transcript_version:
                gs = tv.gene_version.gene_symbol
        return gs

    @staticmethod
    def get_for_build(genome_build: GenomeBuild, tags_qs=None, variant_qs=None):
        """ Returns tags visible within a build
            tags_qs - set to filter - default (None) = all tags
            variant_qs - set to filter - default (None) = all variants """
        if tags_qs is None:
            tags_qs = VariantTag.objects.all()

        va_kwargs = {
            "genome_build": genome_build,
            "allele__in": tags_qs.values_list("allele")
        }
        if variant_qs is not None:
            va_kwargs["variant__in"] = variant_qs

        va_qs = VariantAllele.objects.filter(**va_kwargs)
        # Do distinct as we used to get 2x results with MT (which share contigs across builds)
        tags_qs = VariantTag.objects.filter(allele__in=va_qs.values_list("allele", flat=True))
        return tags_qs.distinct()

    @staticmethod
    def variants_for_build_q(genome_build, tags_qs, tag_ids: List[str]) -> Q:
        if tags_qs is None:
            tags_qs = VariantTag.objects.all()
        if tag_ids:
            tags_qs = tags_qs.filter(tag__in=tag_ids)

        return Q(variantallele__genome_build=genome_build,
                 variantallele__allele__in=tags_qs.values_list("allele"))

analysis/models/mutational_signatures.py
from django.contrib.postgres.fields.array import ArrayField
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import FloatField

from analysis.models.enums import MinimisationResultType, MinimisationStrategy
from snpdb.models import Sample, SoftwareVersion
from snpdb.models.models_enums import ImportStatus


class MutationalSignatureCalculator(SoftwareVersion):
    num_iterations = models.IntegerField()
    sampling_fraction = models.FloatField()
    signature_data_filename = models.TextField()
    minimisation_strategy = models.CharField(max_length=2, choices=MinimisationStrategy.choices)

    class Meta:
        unique_together = ("name", "version", "num_iterations", "sampling_fraction", "signature_data_filename", "minimisation_strategy")


class MutationalSignature(models.Model):
    sample = models.ForeignKey(Sample, on_delete=CASCADE)
    calculator = models.ForeignKey(MutationalSignatureCalculator, on_delete=CASCADE)
    import_status = models.CharField(max_length=1, choices=ImportStatus.choices, default=ImportStatus.CREATED)
    summary = models.TextField()
    mean = ArrayField(FloatField(), null=True)
    num_snps = models.IntegerField(null=True)

    class Meta:
        unique_together = ("sample", "calculator")

    def __str__(self):
        if self.import_status == ImportStatus.SUCCESS:
            description = self.summary
        else:
            import_status = self.get_import_status_display()
            description = f"MutationalSignature {self.pk}, import_status={import_status}"
        return description


class MutationalSignatureMinimisationResult(models.Model):
    mutational_signature = models.ForeignKey(MutationalSignature, on_delete=CASCADE)
    result_type = models.CharField(max_length=1, choices=MinimisationResultType.choices)
    iteration = models.IntegerField()
    solution_array = ArrayField(FloatField())
    fit_data = ArrayField(FloatField())
    diff_data = ArrayField(FloatField())
    ls_sum_diff = models.FloatField()
    la_sum_diff = models.FloatField()

    class Meta:
        unique_together = ("mutational_signature", "result_type", "iteration")


class MutationalSignatureMutationCount(models.Model):
    mutational_signature = models.ForeignKey(MutationalSignature, on_delete=CASCADE)
    mutation_type = models.TextField()
    count = models.IntegerField()

analysis/templates/analysis/analysis_editor_and_grid.html
{% load static %}
<div id="analysis-editor-and-grid">

<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
{% if stand_alone %}
<!-- Importing headers due to stand alone window -->
<link href="{% static 'js/lib/jquery-ui-1.13.2.custom/jquery-ui.min.css' %}" rel="stylesheet">
<link href="{% static 'js/lib/jquery-ui-1.13.2.custom/jquery-ui.theme.css' %}" rel="stylesheet">

<link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
<script type="text/javascript" src="{% static 'js/lib/jquery-3.3.1/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lib/jquery-ui-1.13.2.custom/jquery-ui.min.js' %}"></script>
<!-- layout must be after jquery-ui or resize doesn't work -->
<script type="text/javascript" src="{% static 'js/lib/jquery-3.3.1/jquery.layout-1.4.4.js' %}"></script>
<script src="{% static 'js/lib/jquery.blockUI.js' %}"></script>
{% include "analysis/analysis_includes.html" %}
{% endif %}
<script>
	var GRID = "grid";
	var EDITOR = "editor";
	var COMPONENTS_REQUIRED = [EDITOR, GRID];
	var inFormOrLink;
	var grid_and_editor_registry = {}; // Stores by unique_code (node_id_variant_id)

	function hasRequiredComponents(data) {
		var has_required_components = true;		
		for (var i=0 ; i<COMPONENTS_REQUIRED.length ; ++i) {
			var component = COMPONENTS_REQUIRED[i];
			has_required_components &= component in data;
		}
		return has_required_components;
	}

	// Grids and editors load separately, we can make registers here so that 
	// we can call them when both are triggered.
	function registerComponent(unique_code, name, exec_function) {
		if (!exec_function) {
			exec_function = function() { }; // Do nothing
		}
		var data = grid_and_editor_registry[unique_code];
		if (!data) {
			data = {};
			grid_and_editor_registry[unique_code] = data;
		}

		var funcs = data[name];
		if (!funcs) {
			funcs = [];
			data[name] = funcs
		}
		//console.log("Registering code: " + unique_code + " name: " + name);
		funcs.push(exec_function);

		if (hasRequiredComponents(data)) {
			for (k in data) {
				var funcs = data[k];
				for (var i=0 ; i<funcs.length ; ++i) {
					var func = funcs[i];
					func();
				}
			}
			delete grid_and_editor_registry[unique_code];
		}
	}
	

	$(document).ready(function() {
		layout_analysis_editor_and_grid();

		$('a').on('click', function() { inFormOrLink = true; });
		$('form').on('submit', function() { inFormOrLink = true; });
		
		$(window).on("beforeunload", function() { 
			if (!inFormOrLink) {
				getAnalysisWindow().secondWindowClosing();
			}
		});

	});
</script>
<style>
/* Grid keeps getting cut off, make a bottom margin size of top bar */
#node-grid-container {
    margin-bottom: 50px;
}
</style>
<div id="grid-and-editor-container">
	<div id="node-editor-container">
		<div style='display: none' class='cancel-node-loading'>
			<button>Cancel</button> - Cancel loading node.
		</div> 
		
		<div class="node-editor" id="no-editor">
		</div>
	</div>
	<div id="node-grid-container">
		<div id="error-container">
		</div>
		<div id="node-data-container">
		</div>
	</div>
</div>

</div>

<div id='overlay-container' style='display: none'>
    <!-- Style needs to be in here so when we shift into DOM it stays with overlay until removed in base editor everythingLoaded callback -->
    <style>
    #overlay-container {
        z-index: 10000;
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        margin: auto;
        background-color: #ffffff;
    }
    
    #loading-overlay {
        position: absolute;
        top: 50%;
        left: 50%;
        border: 2px solid #888888;
        opacity: 1.0;
        padding: 50px;
        transform: translate(-50%, -50%);
    }
    
    #animation-container {
        float: left;
    }
    
    #loading-message-container {
        padding-left: 20px;
        width: 80px;
        height: 180px;
        float: right;
        text-align: center;
    }
    
    
    #inner-loading-message {
        position: absolute;
        top: 50%;
        transform: translate(0, -50%);
    }
    
    #inner-loading-message span {
        margin-bottom: 20px;
    }
    
    #node-load-cancel {
        display: none;
    }
    
    </style>

    <div id='loading-overlay'>
        <div id='animation-container'></div>
        <div id='loading-message-container'>
            <div id='inner-loading-message'>
                <span>Loading...</span>
                <p id='node-load-cancel'>
                <button class="btn btn-primary">Cancel Load</button>
                </p>
            </div>
        </div>
    </div>
</div>

analysis/templates/analysis/analysis_templates.html
{% extends menu_analysis_base %}
{% load static %}
{% load ui_help %}
{% load ui_utils %}
{% load crispy_forms_field %}
{% load crispy_forms_tags %}
{% load jqgrid_tags %}
{% block title %}VariantGrid: Analysis templates{% endblock title %}

{% block submenu_page_content %}
<script>
    $(document).ready(() => {
        jQuery.extend($.fn.fmatter , {
            analysisLink : function(cellvalue, options, rowObject) {
                let analysisLink = linkFormatter(cellvalue, options, rowObject);
                return "<span>" + analysisLink + "</span>";
            }
        });

        $('#id_analysis').change(function () {
            const analysisId = $("#id_analysis").val();
            window.location = Urls.analysis(analysisId);
        });
    });
</script>

<div class="container">
    {% page_help page_id='analysis/analysis_templates_help' title='Analyses Templates' %}

    <div id="analysis-template-form-container">
      <form id="analysis-template-form" method="post">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">Create Template</div>
            <div class="card-body">
                {% crispy create_analysis_template_form %}
            </div>
        </div>
      </form>
    </div>

    <form>
        {% labelled label="Open Analysis Template" %}{{ analysis_template_choice_form.analysis }} {{ analysis_template_choice_form.media }}{% endlabelled %}
    </form>

</div>
<div class="container-table">
    {% user_data_grid_filter 'analysis_templates' 'Analysis Templates' %}
    {% jqgrid 'analysis_templates_grid' 'analysis_templates' search=False delete=True %}
</div>

{% endblock submenu_page_content %}

analysis/templates/analysis/node_method_description.html
{% load text_tags %}

<div>
{% for node in nodes %}
	<a name="node-description-{{ node.pk }}"></a>
	{% render_node_text node %}
{% endfor %}
</div>

analysis/templates/analysis/view_mutational_signature.html
{% extends menu_analysis_base %}
{% load static %}
{% load js_tags %}

{% block title %}Mutational Signature{% endblock title %}

{% block head %}
{{ block.super }}
<style>
#mutational-signatures-data {
    width: 100%;
}
</style>
<script type="text/javascript" src="{% static 'js/lib/plotly-latest.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plotly_helper.js' %}"></script>
<script>
let labels = {{ labels | jsonify }};
let bootstrapMatrix = {{ sorted_bootstrap_transposed | jsonify }};

let mutation_types = {{ mutation_types | jsonify }};
let mutation_type_counts = {{ mutation_type_counts | jsonify }};

function plotMutationalSignatures(width, height) {
    var data = getBoxDataFromLabelsMatrix(labels, bootstrapMatrix);
    var layout = defaultLayout("Mutational Signatures", width, height);
    layout["showlegend"] = false;
    Plotly.newPlot("bootstrap-data-graph", data, layout);
}

function plotDataFit(width, height) {
    plotBarArrays("data-fit-graph", "Mutation Counts", mutation_types, mutation_type_counts, width, height);
}



</script>
{% endblock head %}

{% block jsdocumentready %}

var width = $("#mutational-signatures-data").width() * .9;
plotMutationalSignatures(width, width * .25);
plotDataFit(width, width * .25);


$("#show-mut-sig-info").change(function() {
    var mutSigInfo = $(".mut-sig-info");
    if ($(this).is(":checked")) {
        mutSigInfo.show();
    } else {
        mutSigInfo.hide();
    }
});

{% endblock jsdocumentready %}

{% block submenu_page_content %}

<h3>Mutational Signature for {{ mutational_signature.sample.name }}</h3>

<table>
<tr><th>Sample <td><a href="{% url 'view_sample' mutational_signature.sample.pk %}">{{ mutational_signature.sample }}</a>
<tr><th>Summary<td> {{ mutational_signature }}
<tr><th># snps<td> {{ mutational_signature.num_snps }}
<tr><th>Iterations <td> {{ mutational_signature.calculator.num_iterations }}
<tr><th>Sampling Fraction <td> {{ mutational_signature.calculator.sampling_fraction }}
<tr><th>Minimisation Strategy <td> {{ mutational_signature.calculator.get_minimisation_strategy_display }}
</table>

<div id='mutational-signatures-data'>
    <div id='bootstrap-data-graph'></div>

    <div id='data-fit-graph'></div>

    <div id='residues-graph'></div>

    <input id='show-mut-sig-info' type="checkbox" checked> Show signature information
    <table>
    <tr><th>Signature <th>Mean <th>Std
        <th class='mut-sig-info'>Cancer Types
        <th class='mut-sig-info'>Proposed aetiology
        <th class='mut-sig-info'>Additional Features
        <th class='mut-sig-info'>Comments
    {% for signature, mean, std, info in sorted_data %}
    <tr><th>{{ signature }}
        <td>{{ mean }}
        <td>{{ std }}
        <td class='mut-sig-info'>{{ info.cancer_types }}
        <td class='mut-sig-info'>{{ info.proposed_aetiology }}
        <td class='mut-sig-info'>{{ info.additional_mutational_features }}
        <td class='mut-sig-info'>{{ info.comments }}
    {% endfor %}
    </table>

</div>



{% endblock submenu_page_content %}